### ISSUE TITLE
provide method to get IP address

### ISSUE THREAD

**Issue by eighthave** [mvdan/libaccesspoint#1]
It would be very useful to be able to get the IP address of the hotspot.  I have found that `wifiManager.getConnectionInfo()` returns `0` for the IP address and `WifiStateChangeReceiver` thinks there is no connection.  But from the command line, I can get the IP address using `ifconfig`, so there has got to be a way to get it.

**Comment by mvdan** [comment]
For the record: https://stackoverflow.com/questions/14080573/getting-wifi-broadcast-address-in-android-wifi-hotspot/14081716#14081716

**Comment by mvdan** [comment]
Yet to be tested, but implemented from scratch in a different way.

**Comment by mvdan** [comment]
Tested it with the example app now bundled in the repo. Returns the proper IP if an access point is set up, `null` otherwise. I don't know why it returns null if you have an IP address via e.g. being connected to another device as a client, but anyway we want this behaviour.
