### ISSUE TITLE
Support for band and channel selection.

### ISSUE THREAD

**Issue by forlayo** [mvdan/libaccesspoint#13]
Please add support for band and channel selection, which can be done through reflection over wificonfiguration

```
/**
     * 2GHz band.
     * @hide
     */
    public static final int AP_BAND_2GHZ = 0;

    /**
     * 5GHz band.
     * @hide
     */
    public static final int AP_BAND_5GHZ = 1;

    /**
     * The band which AP resides on
     * 0-2G  1-5G
     * By default, 2G is chosen
     * @hide
     */
    public int apBand = AP_BAND_2GHZ;

    /**
     * The channel which AP resides on,currently, US only
     * 2G  1-11
     * 5G  36,40,44,48,149,153,157,161,165
     * 0 - find a random available channel according to the apBand
     * @hide
     */
    public int apChannel = 0;
```

Thanks :)

**Comment by mvdan** [comment]
Care to send a patch? I'll be happy to review.

**Comment by forlayo** [comment]
@mvdan sure, I've just send you a pull request to add this 

https://github.com/mvdan/accesspoint/pull/14/commits/d67b497e95d0ec6120d8e1219400b91917406e8e

**Comment by mvdan** [comment]
It's been almost a year and the posted PR was never finalised, so I'm going to close this as I have no intention to work on it myself.
