### ISSUE TITLE
Android 7.1: Access point created but no internet connection

### ISSUE THREAD

**Issue by philipp-mohr** [mvdan/libaccesspoint#16]
Hi,

I tried to manage my accesspoint with your library on a OnePlus3 running android 7.1. To avoid any mistakes in my implementation I tested your sample app.

Enabling a hotspot works fine. Also another wireless device is able to find the hotspot and connect to it. Unfortunately the device says that there is no connection to the internet. If I manually enable the hotspot through android settings the internet connection works fine.

Can I do something about it or is this a bug related to android 7.1 or my OnePlus 3?

Is this issue caused for the same reason as in this [post ](https://github.com/mvdan/accesspoint/issues/10)?

**Comment by mvdan** [comment]
Yes, this is a duplicate. Unfortunately we haven't found a fix for that issue.
