### ISSUE TITLE
Only catch reflection exceptions

### ISSUE THREAD

**Issue by pserwylo** [mvdan/libaccesspoint#3]
With regards to the API design, I'd suggest only catching the most specific exceptions that are relevant to you. For example, most of the methods which invoke methods via reflection do it like so:

```
public boolean isWifiApEnabled() {
    try {
        return (Boolean) isWifiApEnabled.invoke(wm);
    } catch (Exception e) {
        Log.e(TAG, "", e);
    }
    return false;
}
```

I'd suggest only catching the exceptions to do with reflection. That way, if a genuine exception occurs inside one of the hidden API methods, then it will get thrown to the consumer of your API.

The tricky part is trying to identify if there are any checked exceptions (ones which _must_ be caught or thrown in the hidden API, because it may well differ depending on the version of Android which provides the API.

I'm happy to submit pull requests for this and other issues I'll submit, just documenting now for prosterity.

**Comment by mvdan** [comment]
I'm thinking that I should probably not catch any exception. If the reflection `invoke()` call fails, silently logging the error and returning a zero value - `false`, `null`, `-1`, etc - doesn't seem like the best approach.

What do you think?
