### ISSUE TITLE
Remove getInstance() method with no args

### ISSUE THREAD

**Issue by pserwylo** [mvdan/libaccesspoint#4]
I propose removing the `WifiApControl.getInstance()` method which _doesn't_ take a `Context` as an argument.

As a general principle, it is a good idea to have code behave in such a way that you don't need to know what has happened in the past. Otherwise, when reading a line of code which invokes this method, a reviewer of the code will have to ask themselves:

> "Has something, somewhere in the past, invoked `WifiApControl.getInstance(Context)`? If so, will this _always_ be the case?"

Given that it is not uncommon in Android development to ask for a `Context`, I think it is much safer to _always_ ask for a `Context` in order to get access to a `WifiApControl` instance. If the consumer of your API does not have access to a `Context`, that is not the problem of libaccesspoint, but rather the problem of the consumer. They should be responsible for ensuring there is always a `Context` available at the time they need to get an instance of `WifiApControl.getInstance(...)`.

An API which makes it hard to shoot yourself in the foot is a good API in my book.

**Comment by mvdan** [comment]
Agreed.
