### ISSUE TITLE
Broken on 6.0+

### ISSUE THREAD

**Issue by keag-dev** [mvdan/libaccesspoint#6]
When attempting to use the library on several 6.0 Nexus 5 the access point is neither configured or enabled.

The following error is seen in logcat:

'W/WifiApControl: None found - falling back to the default device name: wlan0'

Got a bunch of 5.1.1 devices that this works on without issue.

**Comment by mvdan** [comment]
Did you try running the example application?

On my Nexus 6 running 6.0, I also get that logcat line, but since my wireless device is indeed wlan0, it does work.

**Comment by mvdan** [comment]
There is now a better warning message for 6.0+, but wlan0 should work for you and hence the example application should be able to enable/disable the AP.

If not, `adb shell` into your device and do `ip link`. You should see the interface name there.

**Comment by mvdan** [comment]
Huh, it doesn't _actually_ work for me:

```
01-21 20:37:24.840 10482 10482 E WifiApControl: Caused by: java.lang.SecurityException: cc.mvdan.accesspoint.example was not granted  this permission: android.permission.WRITE_SETTINGS.
```

**Comment by mvdan** [comment]
Okay, I need to grab this new permission and do the runtime request that 6.0 added. Might take some time to get it fully working.

**Comment by keag-dev** [comment]
Let me know if you need anything else on my end.

**Comment by sebastianmaz** [comment]
I can confirm that it doesn't work on my Nexus 7 2013 on android 6.0.1 too. It doesn't even enable access point. Do you have any idea how to make it work ?

**Comment by keag-dev** [comment]
Seems like he's working on it as of 3 days ago. It's the weekend, cut him some slack.

**Comment by sebastianmaz** [comment]
Sure, I know. I meant if there is anything I can do to help ?

**Comment by mvdan** [comment]
Well, you can try to get it working and open a PR. I just moved and will be busy for the rest of the coming week, so won't have time for this at least until next weekend.

**Comment by mvdan** [comment]
Okay, so I lied. It mostly works for me, but sometimes it takes a few tries for `WRITE_SETTINGS` to be granted. I'm on a cm13 nightly, so perhaps it's just me.

In any case, that's just the quickly put together example code. The library code is pretty much done and trivial. Test away!

**Comment by mvdan** [comment]
Remember to let me know whether current master works for you or not. AFAIK the library code is fine, so unless proven otherwise I'll assume it's ready and tag a release.

**Comment by keag-dev** [comment]
Confirmed working across multiple 6.0+ devices when we request the WRITE_SETTINGS permission. No change to the function of older devices. Release away sir.

**Comment by mvdan** [comment]
Done.
