### ISSUE TITLE
Is it possible to set the wifi channel?

### ISSUE THREAD

**Issue by fabrizi0** [mvdan/libaccesspoint#7]
Hello, is it possible to set the wifi channel?
Thank you.

**Comment by mvdan** [comment]
On 6.0, the only thing I see in "set up wi-fi hotspot" is selecting between 2.4GHz and 5GHz.

Is this possible at all in Android?

**Comment by mvdan** [comment]
Apparently possible via a hidden field: http://stackoverflow.com/a/18958743

Patches welcome.

**Comment by mvdan** [comment]
Actually, can't find that field anywhere in the sources. So back to wondering whether this is possible at all in AOSP.

**Comment by mvdan** [comment]
So it's not possible as far as I can tell. Feel free to reopen if you find a way to do it that will work on plain AOSP (and not just some flavor like Cyanogenmod).
