### ISSUE TITLE
Configurations are not applied

### ISSUE THREAD

**Issue by mhddurrah** [mvdan/libaccesspoint#8]
Trying to setup an access point on Android 6.0.1, I can start the access point mode but the configurations are not applied correctly, the default network-name and password are set.

**Comment by mvdan** [comment]
Is this something limited to newer versions of Android?

It would help if you could set up a variation of the example app in this repo, so that others could reproduce this issue. This would also help test whether the issue is reproducible in earlier Android versions, for example.

**Comment by mhddurrah** [comment]
Thanks for your fast response, I tested it in Android 5.1.1 and worked well, but when I started to test on android 6 (6.0.1 exactly) the issue appeared.
https://gist.github.com/mhddurrah/fe8271e5d366cac0f9d35e5dd60bce84
this is the code snippet I used (almost it is the same as demo :smile:  )

**Comment by mvdan** [comment]
Did you give a read to #6? What version of the library is this on?

**Comment by mhddurrah** [comment]
I have granted WRITE_SETTINGS permissions and every thing is working but ssid and password are not set.

**Comment by mvdan** [comment]
Have you looked at your logcat? There might be sometihng there.

**Comment by mhddurrah** [comment]
Yes, What I got is:

```
W/WifiApControl: 6.0 or later, unaccessible MAC - falling back to the default device name: wlan0
I/WifiManager: setWifiApEnabled : falsepackageName : com.*.ha.android
I/WifiManager: setWifiApEnabled : truepackageName : com.*.ha.android
```

**Comment by mhddurrah** [comment]
Hello mvdan, I have downloaded the library and run the included app but I got the same result, AP can be set but configurations no.

**Comment by mvdan** [comment]
Have you verified if `wlan0` is indeed the name of the wireless device? Something like `ip link` on a shell in the device should tell you.

**Comment by mvdan** [comment]
Reopen if you have any more information or an answer to my question above. There is little I can do without more information.
